# Copyright 2017 Google Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

require 'google/protobuf'

require 'google/protobuf/field_mask_pb'
require 'google/rpc/status_pb'
require 'google/streetview/publish/v1/resources_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.streetview.publish.v1.CreatePhotoRequest" do
    optional :photo, :message, 1, "google.streetview.publish.v1.Photo"
  end
  add_message "google.streetview.publish.v1.GetPhotoRequest" do
    optional :photo_id, :string, 1
    optional :view, :enum, 2, "google.streetview.publish.v1.PhotoView"
  end
  add_message "google.streetview.publish.v1.BatchGetPhotosRequest" do
    repeated :photo_ids, :string, 1
    optional :view, :enum, 2, "google.streetview.publish.v1.PhotoView"
  end
  add_message "google.streetview.publish.v1.BatchGetPhotosResponse" do
    repeated :results, :message, 1, "google.streetview.publish.v1.PhotoResponse"
  end
  add_message "google.streetview.publish.v1.PhotoResponse" do
    optional :status, :message, 1, "google.rpc.Status"
    optional :photo, :message, 2, "google.streetview.publish.v1.Photo"
  end
  add_message "google.streetview.publish.v1.ListPhotosRequest" do
    optional :view, :enum, 1, "google.streetview.publish.v1.PhotoView"
    optional :page_size, :int32, 2
    optional :page_token, :string, 3
    optional :filter, :string, 4
  end
  add_message "google.streetview.publish.v1.ListPhotosResponse" do
    repeated :photos, :message, 1, "google.streetview.publish.v1.Photo"
    optional :next_page_token, :string, 2
  end
  add_message "google.streetview.publish.v1.UpdatePhotoRequest" do
    optional :photo, :message, 1, "google.streetview.publish.v1.Photo"
    optional :update_mask, :message, 2, "google.protobuf.FieldMask"
  end
  add_message "google.streetview.publish.v1.BatchUpdatePhotosRequest" do
    repeated :update_photo_requests, :message, 1, "google.streetview.publish.v1.UpdatePhotoRequest"
  end
  add_message "google.streetview.publish.v1.BatchUpdatePhotosResponse" do
    repeated :results, :message, 1, "google.streetview.publish.v1.PhotoResponse"
  end
  add_message "google.streetview.publish.v1.DeletePhotoRequest" do
    optional :photo_id, :string, 1
  end
  add_message "google.streetview.publish.v1.BatchDeletePhotosRequest" do
    repeated :photo_ids, :string, 1
  end
  add_message "google.streetview.publish.v1.BatchDeletePhotosResponse" do
    repeated :status, :message, 1, "google.rpc.Status"
  end
  add_enum "google.streetview.publish.v1.PhotoView" do
    value :BASIC, 0
    value :INCLUDE_DOWNLOAD_URL, 1
  end
end

module Google
  module Streetview
    module Publish
      module V1
        CreatePhotoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.CreatePhotoRequest").msgclass
        GetPhotoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.GetPhotoRequest").msgclass
        BatchGetPhotosRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.BatchGetPhotosRequest").msgclass
        BatchGetPhotosResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.BatchGetPhotosResponse").msgclass
        PhotoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.PhotoResponse").msgclass
        ListPhotosRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.ListPhotosRequest").msgclass
        ListPhotosResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.ListPhotosResponse").msgclass
        UpdatePhotoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.UpdatePhotoRequest").msgclass
        BatchUpdatePhotosRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.BatchUpdatePhotosRequest").msgclass
        BatchUpdatePhotosResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.BatchUpdatePhotosResponse").msgclass
        DeletePhotoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.DeletePhotoRequest").msgclass
        BatchDeletePhotosRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.BatchDeletePhotosRequest").msgclass
        BatchDeletePhotosResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.BatchDeletePhotosResponse").msgclass
        PhotoView = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.PhotoView").enummodule
      end
    end
  end
end
