# Copyright 2017 Google Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/resources.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'google/type/latlng_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "google.streetview.publish.v1.UploadRef" do
    optional :upload_url, :string, 1
  end
  add_message "google.streetview.publish.v1.PhotoId" do
    optional :id, :string, 1
  end
  add_message "google.streetview.publish.v1.Pose" do
    optional :lat_lng_pair, :message, 1, "google.type.LatLng"
    optional :altitude, :double, 2
    optional :heading, :double, 3
    optional :pitch, :double, 4
    optional :roll, :double, 5
  end
  add_message "google.streetview.publish.v1.Place" do
    optional :place_id, :string, 1
  end
  add_message "google.streetview.publish.v1.Connection" do
    optional :target, :message, 1, "google.streetview.publish.v1.PhotoId"
  end
  add_message "google.streetview.publish.v1.Photo" do
    optional :photo_id, :message, 1, "google.streetview.publish.v1.PhotoId"
    optional :upload_reference, :message, 2, "google.streetview.publish.v1.UploadRef"
    optional :download_url, :string, 3
    optional :thumbnail_url, :string, 9
    optional :share_link, :string, 11
    optional :pose, :message, 4, "google.streetview.publish.v1.Pose"
    repeated :connections, :message, 5, "google.streetview.publish.v1.Connection"
    optional :capture_time, :message, 6, "google.protobuf.Timestamp"
    repeated :places, :message, 7, "google.streetview.publish.v1.Place"
    optional :view_count, :int64, 10
  end
end

module Google
  module Streetview
    module Publish
      module V1
        UploadRef = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.UploadRef").msgclass
        PhotoId = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.PhotoId").msgclass
        Pose = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.Pose").msgclass
        Place = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.Place").msgclass
        Connection = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.Connection").msgclass
        Photo = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.streetview.publish.v1.Photo").msgclass
      end
    end
  end
end
