<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request to update the metadata of photos.
 * Updating the pixels of photos is not supported.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.BatchUpdatePhotosRequest</code>
 */
class BatchUpdatePhotosRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Required. List of update photo requests.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.UpdatePhotoRequest update_photo_requests = 1;</code>
     */
    private $update_photo_requests;

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Rpcmessages::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Required. List of update photo requests.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.UpdatePhotoRequest update_photo_requests = 1;</code>
     */
    public function getUpdatePhotoRequests()
    {
        return $this->update_photo_requests;
    }

    /**
     * <pre>
     * Required. List of update photo requests.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.UpdatePhotoRequest update_photo_requests = 1;</code>
     */
    public function setUpdatePhotoRequests(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Streetview\Publish\V1\UpdatePhotoRequest::class);
        $this->update_photo_requests = $arr;
    }

}

