<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response to batch get of photos.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.BatchGetPhotosResponse</code>
 */
class BatchGetPhotosResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * List of results for each individual photo requested, in the same order as
     * the request.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.PhotoResponse results = 1;</code>
     */
    private $results;

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Rpcmessages::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * List of results for each individual photo requested, in the same order as
     * the request.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.PhotoResponse results = 1;</code>
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * <pre>
     * List of results for each individual photo requested, in the same order as
     * the request.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.PhotoResponse results = 1;</code>
     */
    public function setResults(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Streetview\Publish\V1\PhotoResponse::class);
        $this->results = $arr;
    }

}

