<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/resources.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * A connection is the link from a source photo to a destination photo.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.Connection</code>
 */
class Connection extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Required. The destination of the connection from the containing photo to
     * another photo.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoId target = 1;</code>
     */
    private $target = null;

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Required. The destination of the connection from the containing photo to
     * another photo.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoId target = 1;</code>
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * <pre>
     * Required. The destination of the connection from the containing photo to
     * another photo.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoId target = 1;</code>
     */
    public function setTarget(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Streetview\Publish\V1\PhotoId::class);
        $this->target = $var;
    }

}

