<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request to delete a photo.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.DeletePhotoRequest</code>
 */
class DeletePhotoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Required. ID of the photo.
     * </pre>
     *
     * <code>string photo_id = 1;</code>
     */
    private $photo_id = '';

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Rpcmessages::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Required. ID of the photo.
     * </pre>
     *
     * <code>string photo_id = 1;</code>
     */
    public function getPhotoId()
    {
        return $this->photo_id;
    }

    /**
     * <pre>
     * Required. ID of the photo.
     * </pre>
     *
     * <code>string photo_id = 1;</code>
     */
    public function setPhotoId($var)
    {
        GPBUtil::checkString($var, True);
        $this->photo_id = $var;
    }

}

