<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Request to get a photo.
 * By default
 * - does not return the download URL for the photo bytes.
 * Parameters:
 * - 'view' controls if the download URL for the photo bytes will be returned.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.GetPhotoRequest</code>
 */
class GetPhotoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Required. ID of the photo.
     * </pre>
     *
     * <code>string photo_id = 1;</code>
     */
    private $photo_id = '';
    /**
     * <pre>
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     */
    private $view = 0;

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Rpcmessages::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Required. ID of the photo.
     * </pre>
     *
     * <code>string photo_id = 1;</code>
     */
    public function getPhotoId()
    {
        return $this->photo_id;
    }

    /**
     * <pre>
     * Required. ID of the photo.
     * </pre>
     *
     * <code>string photo_id = 1;</code>
     */
    public function setPhotoId($var)
    {
        GPBUtil::checkString($var, True);
        $this->photo_id = $var;
    }

    /**
     * <pre>
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     */
    public function getView()
    {
        return $this->view;
    }

    /**
     * <pre>
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     */
    public function setView($var)
    {
        GPBUtil::checkEnum($var, \Google\Streetview\Publish\V1\PhotoView::class);
        $this->view = $var;
    }

}

