<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

/**
 * <pre>
 * Specifies which view of the `Photo` should be included in the response.
 * </pre>
 *
 * Protobuf enum <code>google.streetview.publish.v1.PhotoView</code>
 */
class PhotoView
{
    /**
     * <pre>
     * Server reponses do not include the download URL for the photo bytes.
     * The default value.
     * </pre>
     *
     * <code>BASIC = 0;</code>
     */
    const BASIC = 0;
    /**
     * <pre>
     * Server responses include the download URL for the photo bytes.
     * </pre>
     *
     * <code>INCLUDE_DOWNLOAD_URL = 1;</code>
     */
    const INCLUDE_DOWNLOAD_URL = 1;
}

