<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/resources.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Place metadata for an entity.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.Place</code>
 */
class Place extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Required. Place identifier, as described in
     * https://developers.google.com/places/place-id.
     * </pre>
     *
     * <code>string place_id = 1;</code>
     */
    private $place_id = '';

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Required. Place identifier, as described in
     * https://developers.google.com/places/place-id.
     * </pre>
     *
     * <code>string place_id = 1;</code>
     */
    public function getPlaceId()
    {
        return $this->place_id;
    }

    /**
     * <pre>
     * Required. Place identifier, as described in
     * https://developers.google.com/places/place-id.
     * </pre>
     *
     * <code>string place_id = 1;</code>
     */
    public function setPlaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->place_id = $var;
    }

}

