// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/streetview/publish/v1/streetview_publish.proto

package publish

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf4 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for StreetViewPublishService service

type StreetViewPublishServiceClient interface {
	// Creates an upload session to start uploading photo data. The upload URL of
	// the returned `UploadRef` is used to upload the data for the photo.
	//
	// After the upload is complete, the `UploadRef` is used with
	// `StreetViewPublishService:CreatePhoto()` to create the `Photo` object
	// entry.
	StartUpload(ctx context.Context, in *google_protobuf4.Empty, opts ...grpc.CallOption) (*UploadRef, error)
	// After the client finishes uploading the photo with the returned
	// `UploadRef`, `photo.create` publishes the uploaded photo to Street View on
	// Google Maps.
	//
	// This method returns the following error codes:
	//
	// * `INVALID_ARGUMENT` if the request is malformed.
	// * `NOT_FOUND` if the upload reference does not exist.
	CreatePhoto(ctx context.Context, in *CreatePhotoRequest, opts ...grpc.CallOption) (*Photo, error)
	// Gets the metadata of the specified `Photo`.
	//
	// This method returns the following error codes:
	//
	// * `PERMISSION_DENIED` if the requesting user did not create the requested
	// photo.
	// * `NOT_FOUND` if the requested photo does not exist.
	GetPhoto(ctx context.Context, in *GetPhotoRequest, opts ...grpc.CallOption) (*Photo, error)
	// Gets the metadata of the specified `Photo` batch.
	//
	// Note that if `photos.batchGet` fails, either critical fields are
	// missing or there was an authentication error.
	// Even if `photos.batchGet` succeeds, there may have been failures
	// for single photos in the batch. These failures will be specified in
	// `BatchGetPhotosResponse.results.status`.
	// See `photo.get` for specific failures that will occur per photo.
	BatchGetPhotos(ctx context.Context, in *BatchGetPhotosRequest, opts ...grpc.CallOption) (*BatchGetPhotosResponse, error)
	// Lists all the photos that belong to the user.
	ListPhotos(ctx context.Context, in *ListPhotosRequest, opts ...grpc.CallOption) (*ListPhotosResponse, error)
	// Updates the metadata of a photo, such as pose, place association, etc.
	// Changing the pixels of a photo is not supported.
	//
	// This method returns the following error codes:
	//
	// * `PERMISSION_DENIED` if the requesting user did not create the requested
	// photo.
	// * `INVALID_ARGUMENT` if the request is malformed.
	// * `NOT_FOUND` if the photo ID does not exist.
	UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*Photo, error)
	// Updates the metadata of photos, such as pose, place association, etc.
	// Changing the pixels of a photo is not supported.
	//
	// Note that if `photos.batchUpdate` fails, either critical fields
	// are missing or there was an authentication error.
	// Even if `photos.batchUpdate` succeeds, there may have been
	// failures for single photos in the batch. These failures will be specified
	// in `BatchUpdatePhotosResponse.results.status`.
	// See `UpdatePhoto` for specific failures that will occur per photo.
	BatchUpdatePhotos(ctx context.Context, in *BatchUpdatePhotosRequest, opts ...grpc.CallOption) (*BatchUpdatePhotosResponse, error)
	// Deletes a photo and its metadata.
	//
	// This method returns the following error codes:
	//
	// * `PERMISSION_DENIED` if the requesting user did not create the requested
	// photo.
	// * `NOT_FOUND` if the photo ID does not exist.
	DeletePhoto(ctx context.Context, in *DeletePhotoRequest, opts ...grpc.CallOption) (*google_protobuf4.Empty, error)
	// Deletes a list of photos and their metadata.
	//
	// Note that if `photos.batchDelete` fails, either critical fields
	// are missing or there was an authentication error.
	// Even if `photos.batchDelete` succeeds, there may have been
	// failures for single photos in the batch. These failures will be specified
	// in `BatchDeletePhotosResponse.status`.
	// See `photo.update` for specific failures that will occur per photo.
	BatchDeletePhotos(ctx context.Context, in *BatchDeletePhotosRequest, opts ...grpc.CallOption) (*BatchDeletePhotosResponse, error)
}

type streetViewPublishServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreetViewPublishServiceClient(cc *grpc.ClientConn) StreetViewPublishServiceClient {
	return &streetViewPublishServiceClient{cc}
}

func (c *streetViewPublishServiceClient) StartUpload(ctx context.Context, in *google_protobuf4.Empty, opts ...grpc.CallOption) (*UploadRef, error) {
	out := new(UploadRef)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/StartUpload", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streetViewPublishServiceClient) CreatePhoto(ctx context.Context, in *CreatePhotoRequest, opts ...grpc.CallOption) (*Photo, error) {
	out := new(Photo)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/CreatePhoto", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streetViewPublishServiceClient) GetPhoto(ctx context.Context, in *GetPhotoRequest, opts ...grpc.CallOption) (*Photo, error) {
	out := new(Photo)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/GetPhoto", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streetViewPublishServiceClient) BatchGetPhotos(ctx context.Context, in *BatchGetPhotosRequest, opts ...grpc.CallOption) (*BatchGetPhotosResponse, error) {
	out := new(BatchGetPhotosResponse)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/BatchGetPhotos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streetViewPublishServiceClient) ListPhotos(ctx context.Context, in *ListPhotosRequest, opts ...grpc.CallOption) (*ListPhotosResponse, error) {
	out := new(ListPhotosResponse)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/ListPhotos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streetViewPublishServiceClient) UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*Photo, error) {
	out := new(Photo)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/UpdatePhoto", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streetViewPublishServiceClient) BatchUpdatePhotos(ctx context.Context, in *BatchUpdatePhotosRequest, opts ...grpc.CallOption) (*BatchUpdatePhotosResponse, error) {
	out := new(BatchUpdatePhotosResponse)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/BatchUpdatePhotos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streetViewPublishServiceClient) DeletePhoto(ctx context.Context, in *DeletePhotoRequest, opts ...grpc.CallOption) (*google_protobuf4.Empty, error) {
	out := new(google_protobuf4.Empty)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/DeletePhoto", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streetViewPublishServiceClient) BatchDeletePhotos(ctx context.Context, in *BatchDeletePhotosRequest, opts ...grpc.CallOption) (*BatchDeletePhotosResponse, error) {
	out := new(BatchDeletePhotosResponse)
	err := grpc.Invoke(ctx, "/google.streetview.publish.v1.StreetViewPublishService/BatchDeletePhotos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StreetViewPublishService service

type StreetViewPublishServiceServer interface {
	// Creates an upload session to start uploading photo data. The upload URL of
	// the returned `UploadRef` is used to upload the data for the photo.
	//
	// After the upload is complete, the `UploadRef` is used with
	// `StreetViewPublishService:CreatePhoto()` to create the `Photo` object
	// entry.
	StartUpload(context.Context, *google_protobuf4.Empty) (*UploadRef, error)
	// After the client finishes uploading the photo with the returned
	// `UploadRef`, `photo.create` publishes the uploaded photo to Street View on
	// Google Maps.
	//
	// This method returns the following error codes:
	//
	// * `INVALID_ARGUMENT` if the request is malformed.
	// * `NOT_FOUND` if the upload reference does not exist.
	CreatePhoto(context.Context, *CreatePhotoRequest) (*Photo, error)
	// Gets the metadata of the specified `Photo`.
	//
	// This method returns the following error codes:
	//
	// * `PERMISSION_DENIED` if the requesting user did not create the requested
	// photo.
	// * `NOT_FOUND` if the requested photo does not exist.
	GetPhoto(context.Context, *GetPhotoRequest) (*Photo, error)
	// Gets the metadata of the specified `Photo` batch.
	//
	// Note that if `photos.batchGet` fails, either critical fields are
	// missing or there was an authentication error.
	// Even if `photos.batchGet` succeeds, there may have been failures
	// for single photos in the batch. These failures will be specified in
	// `BatchGetPhotosResponse.results.status`.
	// See `photo.get` for specific failures that will occur per photo.
	BatchGetPhotos(context.Context, *BatchGetPhotosRequest) (*BatchGetPhotosResponse, error)
	// Lists all the photos that belong to the user.
	ListPhotos(context.Context, *ListPhotosRequest) (*ListPhotosResponse, error)
	// Updates the metadata of a photo, such as pose, place association, etc.
	// Changing the pixels of a photo is not supported.
	//
	// This method returns the following error codes:
	//
	// * `PERMISSION_DENIED` if the requesting user did not create the requested
	// photo.
	// * `INVALID_ARGUMENT` if the request is malformed.
	// * `NOT_FOUND` if the photo ID does not exist.
	UpdatePhoto(context.Context, *UpdatePhotoRequest) (*Photo, error)
	// Updates the metadata of photos, such as pose, place association, etc.
	// Changing the pixels of a photo is not supported.
	//
	// Note that if `photos.batchUpdate` fails, either critical fields
	// are missing or there was an authentication error.
	// Even if `photos.batchUpdate` succeeds, there may have been
	// failures for single photos in the batch. These failures will be specified
	// in `BatchUpdatePhotosResponse.results.status`.
	// See `UpdatePhoto` for specific failures that will occur per photo.
	BatchUpdatePhotos(context.Context, *BatchUpdatePhotosRequest) (*BatchUpdatePhotosResponse, error)
	// Deletes a photo and its metadata.
	//
	// This method returns the following error codes:
	//
	// * `PERMISSION_DENIED` if the requesting user did not create the requested
	// photo.
	// * `NOT_FOUND` if the photo ID does not exist.
	DeletePhoto(context.Context, *DeletePhotoRequest) (*google_protobuf4.Empty, error)
	// Deletes a list of photos and their metadata.
	//
	// Note that if `photos.batchDelete` fails, either critical fields
	// are missing or there was an authentication error.
	// Even if `photos.batchDelete` succeeds, there may have been
	// failures for single photos in the batch. These failures will be specified
	// in `BatchDeletePhotosResponse.status`.
	// See `photo.update` for specific failures that will occur per photo.
	BatchDeletePhotos(context.Context, *BatchDeletePhotosRequest) (*BatchDeletePhotosResponse, error)
}

func RegisterStreetViewPublishServiceServer(s *grpc.Server, srv StreetViewPublishServiceServer) {
	s.RegisterService(&_StreetViewPublishService_serviceDesc, srv)
}

func _StreetViewPublishService_StartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf4.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).StartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/StartUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).StartUpload(ctx, req.(*google_protobuf4.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreetViewPublishService_CreatePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).CreatePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/CreatePhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).CreatePhoto(ctx, req.(*CreatePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreetViewPublishService_GetPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).GetPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/GetPhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).GetPhoto(ctx, req.(*GetPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreetViewPublishService_BatchGetPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).BatchGetPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/BatchGetPhotos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).BatchGetPhotos(ctx, req.(*BatchGetPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreetViewPublishService_ListPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).ListPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/ListPhotos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).ListPhotos(ctx, req.(*ListPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreetViewPublishService_UpdatePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).UpdatePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/UpdatePhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).UpdatePhoto(ctx, req.(*UpdatePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreetViewPublishService_BatchUpdatePhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdatePhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).BatchUpdatePhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/BatchUpdatePhotos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).BatchUpdatePhotos(ctx, req.(*BatchUpdatePhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreetViewPublishService_DeletePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).DeletePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/DeletePhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).DeletePhoto(ctx, req.(*DeletePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreetViewPublishService_BatchDeletePhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeletePhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreetViewPublishServiceServer).BatchDeletePhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.streetview.publish.v1.StreetViewPublishService/BatchDeletePhotos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreetViewPublishServiceServer).BatchDeletePhotos(ctx, req.(*BatchDeletePhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreetViewPublishService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.streetview.publish.v1.StreetViewPublishService",
	HandlerType: (*StreetViewPublishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartUpload",
			Handler:    _StreetViewPublishService_StartUpload_Handler,
		},
		{
			MethodName: "CreatePhoto",
			Handler:    _StreetViewPublishService_CreatePhoto_Handler,
		},
		{
			MethodName: "GetPhoto",
			Handler:    _StreetViewPublishService_GetPhoto_Handler,
		},
		{
			MethodName: "BatchGetPhotos",
			Handler:    _StreetViewPublishService_BatchGetPhotos_Handler,
		},
		{
			MethodName: "ListPhotos",
			Handler:    _StreetViewPublishService_ListPhotos_Handler,
		},
		{
			MethodName: "UpdatePhoto",
			Handler:    _StreetViewPublishService_UpdatePhoto_Handler,
		},
		{
			MethodName: "BatchUpdatePhotos",
			Handler:    _StreetViewPublishService_BatchUpdatePhotos_Handler,
		},
		{
			MethodName: "DeletePhoto",
			Handler:    _StreetViewPublishService_DeletePhoto_Handler,
		},
		{
			MethodName: "BatchDeletePhotos",
			Handler:    _StreetViewPublishService_BatchDeletePhotos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/streetview/publish/v1/streetview_publish.proto",
}

func init() {
	proto.RegisterFile("google/streetview/publish/v1/streetview_publish.proto", fileDescriptor2)
}

var fileDescriptor2 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x65, 0x24, 0x10, 0x6c, 0x10, 0x52, 0x17, 0x1a, 0x55, 0x4e, 0x91, 0xc0, 0x48, 0x80,
	0xaa, 0xb2, 0xdb, 0x52, 0x3e, 0xa4, 0x70, 0x4b, 0x41, 0x5c, 0x38, 0x54, 0x8d, 0xca, 0x81, 0x4b,
	0xb5, 0x71, 0xa6, 0x8e, 0x25, 0xc7, 0xbb, 0x78, 0xd7, 0x41, 0x88, 0x8f, 0x43, 0x39, 0x72, 0x83,
	0x0b, 0x6f, 0xc0, 0x03, 0xf1, 0x0a, 0x3c, 0x08, 0xf6, 0x7a, 0x37, 0x76, 0x4b, 0x58, 0xec, 0x93,
	0x93, 0x9d, 0xdf, 0x7f, 0xe6, 0x9f, 0x99, 0xc9, 0x1a, 0x3d, 0x8e, 0x38, 0x8f, 0x12, 0xa0, 0x52,
	0x65, 0x00, 0x6a, 0x11, 0xc3, 0x3b, 0x2a, 0xf2, 0x49, 0x12, 0xcb, 0x19, 0x5d, 0xec, 0x36, 0x4e,
	0x8f, 0xcd, 0x29, 0x11, 0x19, 0x57, 0x1c, 0x6f, 0x56, 0x32, 0x52, 0x03, 0xc4, 0x02, 0x8b, 0x5d,
	0xdf, 0x44, 0x29, 0x13, 0x31, 0x65, 0x69, 0xca, 0x15, 0x53, 0x31, 0x4f, 0x65, 0xa5, 0xf5, 0x07,
	0x26, 0xaa, 0xbf, 0x4d, 0xf2, 0x13, 0x0a, 0x73, 0xa1, 0xde, 0x9b, 0xe0, 0xb6, 0xd3, 0x4f, 0x06,
	0x92, 0xe7, 0x59, 0x08, 0x36, 0x15, 0x71, 0xd3, 0x22, 0x9c, 0x83, 0x94, 0x2c, 0xb2, 0xfc, 0xc3,
	0xaf, 0x08, 0x6d, 0x8c, 0x35, 0xfb, 0xba, 0x60, 0x0f, 0x2a, 0x74, 0x0c, 0xd9, 0x22, 0x0e, 0x01,
	0x0b, 0xd4, 0x1b, 0x2b, 0x96, 0xa9, 0x23, 0x91, 0x70, 0x36, 0xc5, 0x7d, 0x93, 0x9c, 0x58, 0x9f,
	0xe4, 0x45, 0xe9, 0xd3, 0xbf, 0x47, 0x5c, 0xbf, 0x9d, 0x54, 0xea, 0x43, 0x38, 0x09, 0x6e, 0x9d,
	0xfe, 0xfa, 0xfd, 0xfd, 0x82, 0x1f, 0xac, 0x97, 0x5e, 0xc4, 0xac, 0x48, 0x32, 0x94, 0x75, 0xfe,
	0xa1, 0xb7, 0x85, 0x3f, 0xa3, 0xde, 0x7e, 0x06, 0x4c, 0xc1, 0x41, 0x19, 0xc5, 0x3b, 0xee, 0xcc,
	0x0d, 0xf4, 0x10, 0xde, 0xe6, 0x20, 0x95, 0x7f, 0xc7, 0xad, 0xd0, 0x6c, 0xb0, 0xa1, 0x7d, 0xe0,
	0xe0, 0x4a, 0xed, 0xe3, 0xa2, 0x7e, 0xe0, 0x8f, 0xe8, 0xf2, 0x4b, 0x50, 0x55, 0xf1, 0x07, 0xee,
	0x54, 0x96, 0xeb, 0x54, 0x79, 0x53, 0x57, 0xee, 0xe3, 0x1b, 0xcb, 0xca, 0xf4, 0x83, 0x7e, 0x1c,
	0xc7, 0xd3, 0x4f, 0xf8, 0x87, 0x87, 0xae, 0x8d, 0x98, 0x0a, 0x67, 0x36, 0xb7, 0xc4, 0x7b, 0xee,
	0xac, 0x67, 0x69, 0x6b, 0xe5, 0x51, 0x37, 0x91, 0x14, 0xc5, 0x2a, 0x42, 0x30, 0xd0, 0xde, 0xd6,
	0xf1, 0xf5, 0xa5, 0x37, 0x39, 0x9c, 0x18, 0x14, 0x7f, 0xf1, 0x10, 0x7a, 0x15, 0x4b, 0x6b, 0x8b,
	0xba, 0x2b, 0xd4, 0xa4, 0xb5, 0xb4, 0xd3, 0x5e, 0x60, 0xec, 0x60, 0x6d, 0xe7, 0x2a, 0x46, 0xb5,
	0x1d, 0xfc, 0xcd, 0x43, 0xbd, 0x23, 0x31, 0x6d, 0xbb, 0x1f, 0x0d, 0xb4, 0xd3, 0x94, 0xb6, 0x75,
	0xe9, 0xbb, 0xfe, 0xcd, 0xf3, 0x53, 0x22, 0x76, 0x56, 0xa4, 0x18, 0x97, 0xdd, 0x99, 0x9f, 0x1e,
	0x5a, 0xd3, 0x2d, 0x6d, 0x94, 0x93, 0xf8, 0x49, 0x8b, 0x19, 0x34, 0x05, 0xd6, 0xe0, 0xd3, 0xce,
	0x3a, 0xd3, 0xaf, 0xdb, 0xda, 0xf4, 0x20, 0xe8, 0x9f, 0x1f, 0x5f, 0x45, 0x97, 0xff, 0xae, 0x1c,
	0xf5, 0x9e, 0x43, 0x02, 0x2d, 0xbb, 0xd7, 0x40, 0xad, 0xb9, 0x7f, 0xdc, 0x00, 0x76, 0xad, 0xb7,
	0x56, 0xaf, 0xf5, 0xb2, 0x41, 0x8d, 0x8c, 0xed, 0x1a, 0xd4, 0x14, 0x74, 0x69, 0xd0, 0x59, 0xdd,
	0xff, 0x1a, 0x54, 0xd1, 0x45, 0x83, 0x46, 0xa7, 0x1e, 0xba, 0x1f, 0xf2, 0xb9, 0xad, 0x10, 0x01,
	0x27, 0x79, 0x14, 0xae, 0xae, 0x34, 0x5a, 0xfb, 0xeb, 0xde, 0x7c, 0xb3, 0x6f, 0x85, 0x3c, 0x61,
	0x69, 0x44, 0x78, 0x16, 0xd1, 0x08, 0x52, 0xdd, 0x2c, 0x5a, 0x85, 0x8a, 0x17, 0x80, 0x5c, 0x7d,
	0x39, 0x3f, 0x33, 0x1f, 0x27, 0x97, 0x34, 0xbf, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x9d,
	0xfe, 0x1c, 0x89, 0x06, 0x00, 0x00,
}
