<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response to list all photos that belong to a user.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.ListPhotosResponse</code>
 */
class ListPhotosResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * List of photos. There will be a maximum number of items returned based on
     * the page_size field in the request.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Photo photos = 1;</code>
     */
    private $photos;
    /**
     * <pre>
     * Token to retrieve the next page of results, or empty if there are no
     * more results in the list.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Rpcmessages::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * List of photos. There will be a maximum number of items returned based on
     * the page_size field in the request.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Photo photos = 1;</code>
     */
    public function getPhotos()
    {
        return $this->photos;
    }

    /**
     * <pre>
     * List of photos. There will be a maximum number of items returned based on
     * the page_size field in the request.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Photo photos = 1;</code>
     */
    public function setPhotos(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Streetview\Publish\V1\Photo::class);
        $this->photos = $arr;
    }

    /**
     * <pre>
     * Token to retrieve the next page of results, or empty if there are no
     * more results in the list.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * <pre>
     * Token to retrieve the next page of results, or empty if there are no
     * more results in the list.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;
    }

}

