<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response payload for a single `Photo` in batch operations including
 * `BatchGetPhotosRequest` and `BatchUpdatePhotosRequest`.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.PhotoResponse</code>
 */
class PhotoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The status for the operation to get or update a single photo in the batch
     * request.
     * </pre>
     *
     * <code>.google.rpc.Status status = 1;</code>
     */
    private $status = null;
    /**
     * <pre>
     * The photo resource, if the request was successful.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.Photo photo = 2;</code>
     */
    private $photo = null;

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Rpcmessages::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The status for the operation to get or update a single photo in the batch
     * request.
     * </pre>
     *
     * <code>.google.rpc.Status status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <pre>
     * The status for the operation to get or update a single photo in the batch
     * request.
     * </pre>
     *
     * <code>.google.rpc.Status status = 1;</code>
     */
    public function setStatus(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->status = $var;
    }

    /**
     * <pre>
     * The photo resource, if the request was successful.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.Photo photo = 2;</code>
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * <pre>
     * The photo resource, if the request was successful.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.Photo photo = 2;</code>
     */
    public function setPhoto(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Streetview\Publish\V1\Photo::class);
        $this->photo = $var;
    }

}

