<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/resources.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Photo is used to store 360 photos along with photo metadata.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.Photo</code>
 */
class Photo extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Output only. Identifier for the photo, which is unique among all photos in
     * Google.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoId photo_id = 1;</code>
     */
    private $photo_id = null;
    /**
     * <pre>
     * Required (when creating photo). Input only. The resource URL where the
     * photo bytes are uploaded to.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.UploadRef upload_reference = 2;</code>
     */
    private $upload_reference = null;
    /**
     * <pre>
     * Output only. The download URL for the photo bytes. This field is set only
     * when the `view` parameter in a `GetPhotoRequest` is set to
     * `INCLUDE_DOWNLOAD_URL`.
     * </pre>
     *
     * <code>string download_url = 3;</code>
     */
    private $download_url = '';
    /**
     * <pre>
     * Output only. The thumbnail URL for showing a preview of the given photo.
     * </pre>
     *
     * <code>string thumbnail_url = 9;</code>
     */
    private $thumbnail_url = '';
    /**
     * <pre>
     * Output only. The share link for the photo.
     * </pre>
     *
     * <code>string share_link = 11;</code>
     */
    private $share_link = '';
    /**
     * <pre>
     * Pose of the photo.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.Pose pose = 4;</code>
     */
    private $pose = null;
    /**
     * <pre>
     * Connections to other photos. A connection represents the link from this
     * photo to another photo.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Connection connections = 5;</code>
     */
    private $connections;
    /**
     * <pre>
     * Absolute time when the photo was captured.
     * When the photo has no exif timestamp, this is used to set a timestamp in
     * the photo metadata.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp capture_time = 6;</code>
     */
    private $capture_time = null;
    /**
     * <pre>
     * Places where this photo belongs.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Place places = 7;</code>
     */
    private $places;
    /**
     * <pre>
     * Output only. View count of the photo.
     * </pre>
     *
     * <code>int64 view_count = 10;</code>
     */
    private $view_count = 0;

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Output only. Identifier for the photo, which is unique among all photos in
     * Google.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoId photo_id = 1;</code>
     */
    public function getPhotoId()
    {
        return $this->photo_id;
    }

    /**
     * <pre>
     * Output only. Identifier for the photo, which is unique among all photos in
     * Google.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.PhotoId photo_id = 1;</code>
     */
    public function setPhotoId(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Streetview\Publish\V1\PhotoId::class);
        $this->photo_id = $var;
    }

    /**
     * <pre>
     * Required (when creating photo). Input only. The resource URL where the
     * photo bytes are uploaded to.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.UploadRef upload_reference = 2;</code>
     */
    public function getUploadReference()
    {
        return $this->upload_reference;
    }

    /**
     * <pre>
     * Required (when creating photo). Input only. The resource URL where the
     * photo bytes are uploaded to.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.UploadRef upload_reference = 2;</code>
     */
    public function setUploadReference(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Streetview\Publish\V1\UploadRef::class);
        $this->upload_reference = $var;
    }

    /**
     * <pre>
     * Output only. The download URL for the photo bytes. This field is set only
     * when the `view` parameter in a `GetPhotoRequest` is set to
     * `INCLUDE_DOWNLOAD_URL`.
     * </pre>
     *
     * <code>string download_url = 3;</code>
     */
    public function getDownloadUrl()
    {
        return $this->download_url;
    }

    /**
     * <pre>
     * Output only. The download URL for the photo bytes. This field is set only
     * when the `view` parameter in a `GetPhotoRequest` is set to
     * `INCLUDE_DOWNLOAD_URL`.
     * </pre>
     *
     * <code>string download_url = 3;</code>
     */
    public function setDownloadUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_url = $var;
    }

    /**
     * <pre>
     * Output only. The thumbnail URL for showing a preview of the given photo.
     * </pre>
     *
     * <code>string thumbnail_url = 9;</code>
     */
    public function getThumbnailUrl()
    {
        return $this->thumbnail_url;
    }

    /**
     * <pre>
     * Output only. The thumbnail URL for showing a preview of the given photo.
     * </pre>
     *
     * <code>string thumbnail_url = 9;</code>
     */
    public function setThumbnailUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->thumbnail_url = $var;
    }

    /**
     * <pre>
     * Output only. The share link for the photo.
     * </pre>
     *
     * <code>string share_link = 11;</code>
     */
    public function getShareLink()
    {
        return $this->share_link;
    }

    /**
     * <pre>
     * Output only. The share link for the photo.
     * </pre>
     *
     * <code>string share_link = 11;</code>
     */
    public function setShareLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->share_link = $var;
    }

    /**
     * <pre>
     * Pose of the photo.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.Pose pose = 4;</code>
     */
    public function getPose()
    {
        return $this->pose;
    }

    /**
     * <pre>
     * Pose of the photo.
     * </pre>
     *
     * <code>.google.streetview.publish.v1.Pose pose = 4;</code>
     */
    public function setPose(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Streetview\Publish\V1\Pose::class);
        $this->pose = $var;
    }

    /**
     * <pre>
     * Connections to other photos. A connection represents the link from this
     * photo to another photo.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Connection connections = 5;</code>
     */
    public function getConnections()
    {
        return $this->connections;
    }

    /**
     * <pre>
     * Connections to other photos. A connection represents the link from this
     * photo to another photo.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Connection connections = 5;</code>
     */
    public function setConnections(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Streetview\Publish\V1\Connection::class);
        $this->connections = $arr;
    }

    /**
     * <pre>
     * Absolute time when the photo was captured.
     * When the photo has no exif timestamp, this is used to set a timestamp in
     * the photo metadata.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp capture_time = 6;</code>
     */
    public function getCaptureTime()
    {
        return $this->capture_time;
    }

    /**
     * <pre>
     * Absolute time when the photo was captured.
     * When the photo has no exif timestamp, this is used to set a timestamp in
     * the photo metadata.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp capture_time = 6;</code>
     */
    public function setCaptureTime(&$var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->capture_time = $var;
    }

    /**
     * <pre>
     * Places where this photo belongs.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Place places = 7;</code>
     */
    public function getPlaces()
    {
        return $this->places;
    }

    /**
     * <pre>
     * Places where this photo belongs.
     * </pre>
     *
     * <code>repeated .google.streetview.publish.v1.Place places = 7;</code>
     */
    public function setPlaces(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Streetview\Publish\V1\Place::class);
        $this->places = $arr;
    }

    /**
     * <pre>
     * Output only. View count of the photo.
     * </pre>
     *
     * <code>int64 view_count = 10;</code>
     */
    public function getViewCount()
    {
        return $this->view_count;
    }

    /**
     * <pre>
     * Output only. View count of the photo.
     * </pre>
     *
     * <code>int64 view_count = 10;</code>
     */
    public function setViewCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->view_count = $var;
    }

}

