<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/resources.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Upload reference for media files.
 * </pre>
 *
 * Protobuf type <code>google.streetview.publish.v1.UploadRef</code>
 */
class UploadRef extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Required. An upload reference should be unique for each user. It follows
     * the form (depending on which RPC is called):
     * &lt;ul&gt;&lt;li&gt;
     * Photos:
     * "https://streetviewpublish.googleapis.com/media/user/&lt;account_id&gt;/photo/&lt;upload_reference&gt;"
     * &lt;/li&gt;&lt;li&gt;
     * Photo sequences (in the form of videos):
     * "https://streetviewpublish.googleapis.com/media/user/&lt;account_id&gt;/video/&lt;upload_reference&gt;"
     * &lt;/li&gt;&lt;/ul&gt;
     * </pre>
     *
     * <code>string upload_url = 1;</code>
     */
    private $upload_url = '';

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Resources::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Required. An upload reference should be unique for each user. It follows
     * the form (depending on which RPC is called):
     * &lt;ul&gt;&lt;li&gt;
     * Photos:
     * "https://streetviewpublish.googleapis.com/media/user/&lt;account_id&gt;/photo/&lt;upload_reference&gt;"
     * &lt;/li&gt;&lt;li&gt;
     * Photo sequences (in the form of videos):
     * "https://streetviewpublish.googleapis.com/media/user/&lt;account_id&gt;/video/&lt;upload_reference&gt;"
     * &lt;/li&gt;&lt;/ul&gt;
     * </pre>
     *
     * <code>string upload_url = 1;</code>
     */
    public function getUploadUrl()
    {
        return $this->upload_url;
    }

    /**
     * <pre>
     * Required. An upload reference should be unique for each user. It follows
     * the form (depending on which RPC is called):
     * &lt;ul&gt;&lt;li&gt;
     * Photos:
     * "https://streetviewpublish.googleapis.com/media/user/&lt;account_id&gt;/photo/&lt;upload_reference&gt;"
     * &lt;/li&gt;&lt;li&gt;
     * Photo sequences (in the form of videos):
     * "https://streetviewpublish.googleapis.com/media/user/&lt;account_id&gt;/video/&lt;upload_reference&gt;"
     * &lt;/li&gt;&lt;/ul&gt;
     * </pre>
     *
     * <code>string upload_url = 1;</code>
     */
    public function setUploadUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->upload_url = $var;
    }

}

